### ISSUE TITLE
Ergonomically creating a chain of error?

### ISSUE THREAD

**Issue by alexcrichton** [withoutboats/failure#93]
Hello! I figured I'd give porting Cargo over to using `failure` a stab. Cargo uses error-chain's `chain_err` *liberally* all over the place and I was wondering how I might port that over to `failure`.

It seemed like this would originally just be usage of the `with_context` method (or in general the `Context` type) but I think that's not connected to the return value of `Fail::cause`? With Cargo at least we were using the `Fail::cause` chain to print the "caused by ..." for each item as well as iterating over the whole chain to do things like test if it's a spurious network error.

Am I off-base though in thinking that `Context` doesn't quite work for this use case? Or is a "built in" solution for populating `Fail::cause` still in the works perhaps?

**Comment by jsgf** [comment]
I've just been converting a chunk of code to use failure as an experiment, and also did the chain_err -> with_context mapping, and was surprised that `err.with_context(|_| ErrorKind::SomeContext)` did cause the resulting error to be `ErrorKind::SomeContext` with the cause being `err`.

**Comment by jsgf** [comment]
I guess this is not what `Context` is intended for, given:

> The context is intended to be a human-readable, user-facing explanation for the error that has occurred.

However, the API makes it really easy to attach a context at any point, but has no corresponding way to attach a new error to a causal-chain. It seems that the underlying assumption that every error that could be caused by something else will already include that cause explicitly into its structure.

But in practice I've found that the real root-cause error will have some well-defined type, but then the chain leading to it will be little more than string annotations so that that the whole story can be constructed from the full error message.

One possibility might be to couple `failure::err_msg` with `failure::err_cause(cause: impl Fail, msg: &'static str) -> Error` for the informal string description.

**Comment by jsgf** [comment]
Hm, it's awkward because `Error` doesn't itself implement `Fail`, so an `Error` instance can't be directly used as the return from `cause()`. It would require a wrapper type that does implement `Fail`.

**Comment by withoutboats** [comment]
The `Context<D>` should implement `cause` properly, does it not?

**Comment by alexcrichton** [comment]
@withoutboats oh so at least the way that I was planning on using it was to where if I say `let foo error.with_context(context)` then `foo.cause()` would return `Some(&error)` whereas today I think it returns `error.cause()`.

In that sense I'm not sure you can use `with_context` to fill out `cause` if it was `None` before? Although I could very well be missing the location it is actually doing that!

**Comment by withoutboats** [comment]
Talked to @alexcrichton on IRC, the thing he was missing was that `Error::cause` (unlike `Fail::cause`) is really just a conversion method from `&Error` to `&Fail`. I'm pretty confident none of the implementations skip any errors in the cause chain.

**Comment by alexcrichton** [comment]
Indeed! I suspect that my problem isn't actually a problem and I just need to finish fixing the hundreds of compile errors in Cargo instead of postulating about code I'm not running :)

In any case I don't think this'll be an issue so I'm going to close.

**Comment by jsgf** [comment]
> The Context<D> should implement cause properly, does it not?

`Context` doesn't implement `cause()` - it just uses `Fail`'s default implementation which always returns `None`:

```
    impl<D: Display + Send + Sync + 'static> Fail for Context<D> { }
```
